### ISSUE TITLE
Add ISOSTS to HTML conversion script from ISO

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2sts#2]
ISOSTS XML conversion to HTML:
https://www.iso.org/schema/isosts/resources/isosts2html_standalone.xsl

Publish these to gh-pages so we can see the results.

**Comment by Intelligent2013** [comment]
@ronaldtse 

I'm trying to deploy gh-pages, but get this error (https://github.com/metanorma/mn2sts/runs/708958936):
```
ERROR: not found ACTIONS_DEPLOY_KEY, PERSONAL_TOKEN, or GITHUB_TOKEN
```

ubuntu.yml:
```
    - name: GitHub Pages action
      uses: docker://peaceiris/gh-pages:v2
      with:
        emptyCommits: false
        forceOrphan: true
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./published
```

Looks like GH_DEPLOY_KEY doesn't set. Could you set up it?
Thank you.
